### ISSUE TITLE
prefixing sessions? 

### ISSUE THREAD

**Issue by samayo** [simple-mvc-framework/v2#113]
Hi, you have a good looking framework here, as I am learning to make my own, I see something I like, but didn't quite get why you decided to prefix sessions?

**Comment by Oluwafemikorede** [comment]
The idea is to prevent you from destroying other open sessions when destroying a particular web app session. When you destroy session in site a, it doesnt affect site b

**Comment by daveismyname** [comment]
it stops sessions clashing in the event of more then one installation is ran on the same domain, that way you can have a different prefix for each installation.
