### ISSUE TITLE
Site Optimization 

### ISSUE THREAD

**Issue by Oluwafemikorede** [simple-mvc-framework/v2#115]
My site built with smvc framework takes an average of 7s to load. How do I optimize further with framework. Suggestions and tips are welcome.

**Comment by Oluwafemikorede** [comment]
I think a site optimizer helper will do.

**Comment by SecretD** [comment]
Maybe your queries are not optimized. Do you use many joins inside your queries?

**Comment by Volter9** [comment]
@Oluwafemikorede is it takes 7 seconds to load the page itself or also with resources? How do you measure load time?
