### ISSUE TITLE
router.php: autoDispatch() - error handling

### ISSUE THREAD

**Issue by danieljsamson** [simple-mvc-framework/v2#116]
Hi,

router.php: autoDispatch() should use the default controller for "http://server/method"
but it doesn't. instead you get a blank screen. It also doesn't give you an error when it can find something.

So I created a fix:
When you go to "/somthing" it automatically selects the default controller.
However if it finds a controller but not a method it will automatically
choose the default method for that controller. It gives you a 404 error it it can't find a controller and a method.

I have commited this change to my fork: https://github.com/danieljsamson/v2

Feel free to pull it from there.

**Comment by daveismyname** [comment]
thanks I'll run this for awhile to ensure everything is working.

**Comment by danieljsamson** [comment]
Cool,

I couldn't find the design for this item, so I hope that my design is appropriate.

:)

**Comment by daveismyname** [comment]
the main router has been updated now.
