### ISSUE TITLE
Can't Access a Class

### ISSUE THREAD

**Issue by rhizalpatrax64bit** [simple-mvc-framework/v2#123]
Hai,

Class name and file.php not the same, I have a problem when I upload my application to web hosting, (Unix is Case Sensitive)
I mean, if the class name = "App" then the name of the file should be "App.php" not "app.php"

Class 'core\Controller' not found in /home/xxxxx/public_html/report/app/core/model.php on line 11

I found a problem, controller class name is not same with the file name
your controller: "controller.php" but the name of class is "Controller"

you probably understand what I mean.

btw this is very good framework,, i realy enjoyed with this framework.. 
Sory, my english is Bad.. :(

**Comment by bakermanus** [comment]
I have no idea why you are getting this error. I use all of my applications on unix server, and i have never had this issue.

**Comment by SecretD** [comment]
change the 'core/Controller' to 'core/controller' and it should work. This is the reason why we want to use the psr standards see issue #120

**Comment by rhizalpatrax64bit** [comment]
Yes, finally i solved my problem, i change 'core/Controller' to 'core/controller', and for other class too..
and everything is work fine, :)
thanks for your response
