### ISSUE TITLE
Add support to PDO::FETCH_CLASS

### ISSUE THREAD

**Issue by vitortalaia** [simple-mvc-framework/v2#125]
Hi,

The current `select` method doesn't give the option to use the `PDO::FETCH_CLASS` fetch mode. To make it work the `fetchAll` method needs a second argument, a string with the class name.

```php
$stmt->fetchAll($fetchMode, 'Class');
```

I've made the changes in [this PR](https://github.com/simple-mvc-framework/v2/pull/124).

Thanks.

**Comment by daveismyname** [comment]
thanks for that.
